name: grine
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - blas=1.0=mkl
  - blosc=1.17.0
  - bzip2=1.0.8
  - ca-certificates=2019.9.11
  - certifi=2019.9.11
  - cloudpickle=1.2.2
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask-core=2.7.0
  - decorator=4.4.1
  - freetype=2.10.0
  - hdf5=1.10.5
  - icu=64.2
  - imageio=2.6.1
  - intel-openmp=2019.4
  - joblib=0.14.0
  - jpeg=9c
  - kiwisolver=1.1.0
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.0
  - liblapack=3.8.0
  - libpng=1.6.37
  - libtiff=4.1.0
  - lz4-c=1.8.3
  - matplotlib=3.1.2
  - matplotlib-base=3.1.2
  - mkl=2019.4
  - mkl-service=2.3.0
  - mock=3.0.5
  - networkx=2.4
  - numexpr=2.7.0
  - numpy=1.17.3
  - olefile=0.46
  - openssl=1.1.1d
  - pandas=0.25.3
  - pillow=6.2.1
  - pip=19.3.1
  - pyparsing=2.4.5
  - pyqt=5.12.3
  - pytables=3.6.1
  - python=3.7.3
  - python-dateutil=2.8.1
  - python-igraph==0.7.1.post6
  - python-louvain=0.13
  - pytz=2019.3
  - pywavelets=1.1.1
  - qt=5.12.5
  - scikit-image=0.16.2
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - setuptools=41.6.0
  - simplejson=3.16.0
  - six=1.13.0
  - sqlite=3.30.1
  - tk=8.6.9
  - toolz=0.10.0
  - tornado=6.0.3
  - umap-learn=0.3.9
  - wheel=0.33.6
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.4.3
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1